### ISSUE TITLE
NetBitWriter.ReadByte NullReferenceException

### ISSUE THREAD

**Issue by jbruening** [lidgren/lidgren-network-gen3#44] opened 2015-09-26 00:13 UTC
occasionally, NetBuffer.ReadByte is throwing a nullreference on what appears to be a perfectly valid message.

![nullref](https://cloud.githubusercontent.com/assets/1760487/10114596/63c2b8b0-63a8-11e5-939c-e5cd030e38b8.png)

As in the image, the buffer has data (and not visible, but the position is 0), but a nullref is being thrown from NetBitWriter.

built straight from c42b885

**Comment by lidgren** [comment] 2015-09-27 08:29
Duplicate of #45

**Closed by lidgren** 2015-09-27 08:29 UTC
